#!/bin/sh
#
# Write/remove a task to do later.
#
# Select an existing entry to remove it from the file, or type a new entry to
# add it.
#

file="$HOME/notes/todo"
touch "$file"
height=$(wc -l "$file" | awk '{print $1}')
prompt="Add/delete a task: "

aplay -q "$SYSSFX"/in.wav &
cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
		grep -v "^$cmd\$" "$file" > "$file.$$"
		aplay -q "$SYSSFX"/pick.wav &
		mv "$file.$$" "$file"
        height=$(( height - 1 ))
 	else
		echo "$cmd" >> "$file"
		height=$(( height + 1 ))
		aplay -q "$SYSSFX"/next.wav &
 	fi

	cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
done
aplay -q "$SYSSFX"/cancel.wav &

exit 0
